docker:
    path: .
id: 8fabfd35-c278-4478-8222-4eeebe7874e6
ide:
    filename: ide.yaml
name: captstone-llm-jaime
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "2"
